import 'dart:convert';
import 'dart:typed_data';

// Sample images for the "Scan image bytes" demo, embedded as encoded PNG files
// so the demo needs no asset set-up and no file picker plugin. In a real app
// these bytes would come from a picker, the clipboard, a share intent or a
// download.

/// A QR code linking to the issue that asked for bytes support (#199).
final Uint8List sampleQrPng = base64Decode(
  'iVBORw0KGgoAAAANSUhEUgAAAeAAAAFoCAAAAACqXHf8AAAEb0lEQVR42u3cOXbjMBBAQd3/'
  '0nSuwOiNjxBRP7OHpiwWkmkB/lx6dR+PALAAC7AAC7AACzBgARZgARZgARZgwAIswAIswAIs'
  'wAIMWIAFWIAFWIAFGLAAC7AAC7AACzBgARbg/1+o2Oo+q+9//3v0ftmfq74fwIABAwYMGDBg'
  'wIABAwb8buDu9dkFUH2wq5+bej+AAQMGDBgwYMCAAQMGDPgM4BXE6uvodVHo7ILovh/AgAED'
  'BgwYMGDAgAEDBgy4AxW9fxcQMGDAgAEDBgwYMGDAgAEDfgK4OghZDTi6AxbAgAEDBgwYMGDA'
  'gAEDBgz4Gtgonh1YZA9kZze62/gOGDBgwIABAwYMGDBgwIAjb7D6h8N2/dofQgMMGDBgwIAB'
  'AwYMGDBgwE8MSqoHv1fXPwUDGDBgwIABAwYMGDBgwIDfMejIDgqm75PdIL/6/m6DDcCAAQMG'
  'DBgwYMCAAQMG/BuDjixsdkCRXRjd1z3uADhgwIABAwYMGDBgwIABAw4NKKYfeHYwsnr96gLc'
  'ZeABGDBgwIABAwYMGDBgwICfBc4ODrILJAqW/T2zv/+xgw7AgAEDBgwYMGDAgAEDBpx6g9WB'
  'w9RG+anrrk0CDBgwYMCAAQMGDBgwYMB7AE89iO7g4a4N7LvAAwYMGDBgwIABAwYMGDDgZ4Cr'
  'g4e7Hmh2A8HUwgEMGDBgwIABAwYMGDBgwGefD74bYvq67gZ+wIABAwYMGDBgwIABAwZ8BnAV'
  'LrowsgDdgcxdrwsYMGDAgAEDBgwYMGDAgN816MgOBLIDher1d90PMGDAgAEDBgwYMGDAgAED'
  'vgY+6J9+0NHfJ7pB/9iN74ABAwYMGDBgwIABAwYMuDUAmILqbmjPQu9yEBwwYMCAAQMGDBgw'
  'YMCAAT8DPPWgoguj+vrVhbbrwAMwYMCAAQMGDBgwYMCAAe8x6JjaMN49eN09aL6679SCBAwY'
  'MGDAgAEDBgwYMGDAvwlc/X4U8u7BydRGA8CAAQMGDBgwYMCAAQMGfBZw94B3dkCSHax0D3wf'
  'e7IBMGDAgAEDBgwYMGDAgAGH/sOffTDVA93VgUYV8PhJFmDAgAEDBgwYMGDAgAEfCjy1QKY/'
  '0O9urO8OcgADBgwYMGDAgAEDBgwY8LsHHVWg6IOvHiyPDjZ2BwUMGDBgwIABAwYMGDBgwHsB'
  'V6+vfsBePWDeXXDHDjoAAwYMGDBgwIABAwYMGPDoIKH6AXwXZHqjAWDAgAEDBgwYMGDAgAED'
  'Bvxp/KG0KGR1cFIdsEQXJGDAgAEDBgwYMGDAgAEDBnzHoKO7USC6cK5NAgwYMGDAgAEDBgwY'
  'MGDAewBXr48e8K5CVAcTuww2AAMGDBgwYMCAAQMGDBjwXsDTG8i7A5Dsfac34AMGDBgwYMCA'
  'AQMGDBgw4HcCC7AAC7AAAxZgARZgARZgAQYswAIswAIswAIswIAFWIAFWIAFWIABC7AAC7AA'
  'C7AAAxZgARZgARZgARZgwAIswAIswAIswIAFWIAFWIAFWICP7w8vtkrPve8CpAAAAABJRU5E'
  'rkJggg==',
);

/// An EAN-13 barcode for the digits 9780201379624.
final Uint8List sampleEan13Png = base64Decode(
  'iVBORw0KGgoAAAANSUhEUgAAAZAAAADwCAAAAAALV23+AAAB0klEQVR42u3RQQqAMAwAwfz/'
  '03oQRJLGUwW1swcRaW3oxKZXFa4AiIAAERAgAgJEQIAIiIAAERAgAgJEQIAIiIAAERAgAgJE'
  'QIAIiIAAERAgAgJEQIDo0yARcX0ene9pWVqfttTv9yuH/0y7hod2v+2GrCPVld08QIAAAQIE'
  'CBAgQIAAAQIECBAgQIAAAQIECBAgQIAAAQIECBAgQIAAAQIECBAgQIAAAQIECBAgQIAAAQIE'
  'CBAgQIAAAQIECBAgQIAAAQIECBAgQIAAAQIECBAgQIAAAQIECBAgQIAAAQIECBAgQIAAAQIE'
  'CBAgQIAAAQIECBAgQIAAAQIECBAgQIAAAQIECBAgQIAAAQIECBAgQIAAAQIECBAgQIAAAQIE'
  'CBAgQIAAAQIECBAgQIAAAQIECBAgQIAAAQIECBAgQIAAAQIECBAgQIAAAQIECBAgQIAAAQIE'
  'CBAgQIAAAQIECBAgQIAAAQIECBAgQIAAAQIECBAgQIAAAQIECBAgsw6f1Z8mAQIECBAgQIAA'
  'AQIECBAgQFwDECBAgAABsjiIHiF1BUAEBIiAABEQIAICREAEBIiAABEQIAICREAEBIiAABEQ'
  'IAICREAEBIiAABEQIAKyZDsX38JUOUWCYwAAAABJRU5ErkJggg==',
);
